### ISSUE TITLE
Please tag and version this project

### ISSUE THREAD

**Issue by jredville** [pmezard/go-difflib#5]
Tags and versions aid in packaging for things like .deb files, and for anyone wanting to use Glide and other version based package managers to version their dependencies. It would also help ensure that if you make a breaking change, we don't pull it down until we are ready.

**Comment by pmezard** [comment]
Done, sorry for the delay. Tell me if this is not the right way to do it, I do not use vendoring tools.

**Comment by jredville** [comment]
Perfect. Thank you very much!
